# Generated by Django 3.2.4 on 2021-12-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='categoria',
            new_name='category',
        ),
    ]
