# Generated by Django 3.2.4 on 2021-12-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_publication_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(default='spareParts.png', upload_to='Repuestero_Media/publicaciones/carros/'),
        ),
    ]
