# Generated by Django 3.2.4 on 2021-10-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('firts_login', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(default='Client_Media/Imagen_Perfil/user_default_profilepic.png', upload_to='Client_Media/Imagen_Perfil/')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(default=0)),
                ('telefono1', models.IntegerField(default=0)),
                ('telefono2', models.IntegerField(default=0)),
            ],
        ),
    ]
